Repository Azure/Industrial-IoT, pull requests merged in 2020-10, with the labels that each got.

#751 WorkerSupervisor enable the reduction of Worker
  common/src/Microsoft.Azure.IIoT.Agent.Framework/src/Agent/Default/Worker.cs
  common/src/Microsoft.Azure.IIoT.Agent.Framework/src/Agent/Default/WorkerSupervisor.cs
  common/src/Microsoft.Azure.IIoT.Agent.Framework/src/IWorkerSupervisor.cs
  common/src/Microsoft.Azure.IIoT.Agent.Framework/tests/Worker/WorkerSupervisorTests.cs
Labels: Publisher

#761 Optimize performance for extension method "ToMonitoredItemNotifications"
  components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/src/Extensions/MonitoredItemNotificationModelEx.cs
  components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/tests/Microsoft.Azure.IIoT.OpcUa.Protocol.Tests.csproj
  components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/tests/Models/MonitoredItemNotificationsTests.cs
  components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/tests/TestData/DataChangeNotification.json
  components/opc-ua/src/Microsoft.Azure.IIoT.OpcUa.Protocol/tests/TestData/SubscriptionMonitoredItems.json
Labels: Publisher

#768 Avoid NullReferenceException in ModuleProcess
  modules/src/Microsoft.Azure.IIoT.Modules.OpcUa.Publisher/src/ModuleProcess.cs
Labels: Publisher, bug

#819 Avoid NullReferenceException in case of job continuation
  common/src/Microsoft.Azure.IIoT.Agent.Framework/src/Agent/Default/Worker.cs
Labels: Publisher

#835 Publisher 2.5: Use LTS base image for MCR
  modules/src/Microsoft.Azure.IIoT.Modules.Diagnostic/cli/mcr.json
  modules/src/Microsoft.Azure.IIoT.Modules.Discovery/cli/mcr.json
  modules/src/Microsoft.Azure.IIoT.Modules.OpcUa.Publisher/cli/mcr.json
  modules/src/Microsoft.Azure.IIoT.Modules.OpcUa.Twin/cli/mcr.json
  services/src/Microsoft.Azure.IIoT.Services.All/src/mcr.json
  tools/scripts/docker-source.ps1
Labels: Publisher 2.5 or below
