Repository Azure/Industrial-IoT, pull requests merged in 2020-07, with the labels that each got.

#621 Fix broken links due to backslash
  readme.md
Labels: bug, documentation

#634 Engineering tool fixed accepting invalid values
  samples/src/Microsoft.Azure.IIoT.App/src/Models/ListNodeRequested.cs
  samples/src/Microsoft.Azure.IIoT.App/src/Models/PublisherInfoRequested.cs
  samples/src/Microsoft.Azure.IIoT.App/src/Pages/Publishers.razor
  samples/src/Microsoft.Azure.IIoT.App/src/Validation/ListNodeValidator.cs
  samples/src/Microsoft.Azure.IIoT.App/src/Validation/PublisherInfoValidator.cs
Labels: bug

#645 Update deploy.ps1 params
  deploy/scripts/deploy.ps1
  docs/deploy/howto-deploy-all-in-one.md
Labels: documentation
