Repository Azure/Industrial-IoT, pull requests merged in 2020-02, with the labels that each got.

#248 Fixing formatting issues.
  docs/deploy/howto-deploy-aks.md
Labels: bug, documentation

#249 Fixed formatting in docs/deploy/howto-install-iot-edge.md.
  docs/deploy/howto-install-iot-edge.md
Labels: bug, documentation

#252 Docs
  deploy/scripts/deploy.ps1
  deploy/templates/azuredeploy.infrastructure.json
  docs/api/json.md
  docs/api/readme.md
  docs/deploy/howto-deploy-aks.md
  docs/deploy/howto-deploy-all-in-one.md
  docs/deploy/howto-deploy-local.md
  docs/deploy/howto-enable-asc-for-iot-and-sentinel-steps.md
  docs/deploy/howto-install-iot-edge.md
  docs/deploy/howto-run-microservices-locally.md
  docs/deploy/quickstart-gateway-installer.md
  docs/deploy/readme.md
  docs/industrial-iot-components.md
  docs/media/deployed-application.png
  docs/media/deployment-succeeded.png
  docs/media/eng-tool-assets.png
  docs/media/eng-tool-browse.png
  docs/media/eng-tool-discovery-endpoints.PNG
  docs/media/eng-tool-discovery-on.png
  docs/media/eng-tool-discovery.png
  docs/media/eng-tool-gateway.png
  docs/media/eng-tool-home.png
  docs/media/eng-tool-publisher.PNG
  docs/media/tut-power-bi-cdm-step1.png
  docs/media/tut-power-bi-cdm-step2.png
  docs/media/tut-power-bi-cdm-step3.png
  docs/media/tut-power-bi-cdm-step4.png
  docs/media/tut-publish-data-step1.png
  docs/media/tut-publish-data-step2.png
  docs/media/tut-publish-data-step3.png
  docs/media/tut-publish-data-step4.png
  docs/media/tut-tsi-dataaccess1.png
  docs/media/tut-tsi-dataaccess2.png
  docs/media/tut-tsi-dataaccess3.png
  docs/media/tut-tsi-step0.png
  docs/media/tut-tsi-step1.png
  docs/media/tut-tsi-step2.png
  docs/media/tut-tsi-step3.png
  docs/media/tut-tsi-step4.png
  docs/media/tut-tsi-step5.png
  docs/media/tut-tsi-step6.png
  docs/modules/discovery.md
  docs/opcua.md
  docs/readme.md
  docs/services/engineeringtool.md
  docs/services/jobs.md
  docs/services/readme.md
  docs/services/tunnel.md
  docs/services/twin.md
  docs/tutorials/readme.md
  docs/tutorials/tut-discover-assets.md
  docs/tutorials/tut-power-bi-cdm.md
  docs/tutorials/tut-publish-data.md
  docs/tutorials/tut-timeseriesinsights.md
  docs/tutorials/tut-use-cli.md
  docs/tutorials/tut-use-postman.md
  readme.md
Labels: in progress

#269 Fixing access to Swagger in Kubernetes deployment.
  common/src/Microsoft.Azure.IIoT.Abstractions/src/PcsVariable.cs
  common/src/Microsoft.Azure.IIoT.AspNetCore.OpenApi/src/Extensions/ApplicationBuilderEx.cs
  common/src/Microsoft.Azure.IIoT.AspNetCore.OpenApi/src/IOpenApiConfig.cs
  common/src/Microsoft.Azure.IIoT.AspNetCore.OpenApi/src/Runtime/OpenApiConfig.cs
  common/src/Microsoft.Azure.IIoT.AspNetCore/src/AspNetCoreVariable.cs
  common/src/Microsoft.Azure.IIoT.AspNetCore/src/Cors/Runtime/CorsConfig.cs
  common/src/Microsoft.Azure.IIoT.AspNetCore/src/ForwardedHeaders/Extensions/ServiceCollectionEx.cs
  common/src/Microsoft.Azure.IIoT.AspNetCore/src/ForwardedHeaders/IForwardedHeadersConfig.cs
  common/src/Microsoft.Azure.IIoT.AspNetCore/src/ForwardedHeaders/Runtime/ForwardedHeadersConfig.cs
  common/src/Microsoft.Azure.IIoT.Core/src/Auth/Server/IHostConfig.cs
  common/src/Microsoft.Azure.IIoT.Core/src/Auth/Server/Runtime/AuthConfig.cs
  common/src/Microsoft.Azure.IIoT.Core/src/Auth/Server/Runtime/HostConfig.cs
  samples/src/Microsoft.Azure.IIoT.App/src/Runtime/Config.cs
  samples/src/Microsoft.Azure.IIoT.App/src/Startup.cs
  services/src/Microsoft.Azure.IIoT.Services.All/src/Runtime/Config.cs
  services/src/Microsoft.Azure.IIoT.Services.All/src/Startup.cs
  services/src/Microsoft.Azure.IIoT.Services.Common.Configuration/src/Runtime/Config.cs
  services/src/Microsoft.Azure.IIoT.Services.Common.Configuration/src/Startup.cs
  services/src/Microsoft.Azure.IIoT.Services.Common.Hub.Edgemanager/src/Runtime/Config.cs
  services/src/Microsoft.Azure.IIoT.Services.Common.Hub.Edgemanager/src/Startup.cs
  services/src/Microsoft.Azure.IIoT.Services.Common.Jobs.Edge/src/Runtime/Config.cs
  services/src/Microsoft.Azure.IIoT.Services.Common.Jobs.Edge/src/Startup.cs
  services/src/Microsoft.Azure.IIoT.Services.Common.Jobs/src/Runtime/Config.cs
  services/src/Microsoft.Azure.IIoT.Services.Common.Jobs/src/Startup.cs
  services/src/Microsoft.Azure.IIoT.Services.OpcUa.Publisher/src/Runtime/Config.cs
  services/src/Microsoft.Azure.IIoT.Services.OpcUa.Publisher/src/Startup.cs
  services/src/Microsoft.Azure.IIoT.Services.OpcUa.Registry.Onboarding/src/Runtime/Config.cs
  services/src/Microsoft.Azure.IIoT.Services.OpcUa.Registry.Onboarding/src/Startup.cs
  services/src/Microsoft.Azure.IIoT.Services.OpcUa.Registry/src/Runtime/Config.cs
  services/src/Microsoft.Azure.IIoT.Services.OpcUa.Registry/src/Startup.cs
  services/src/Microsoft.Azure.IIoT.Services.OpcUa.Twin.Gateway/src/Runtime/Config.cs
  services/src/Microsoft.Azure.IIoT.Services.OpcUa.Twin.Gateway/src/Startup.cs
  services/src/Microsoft.Azure.IIoT.Services.OpcUa.Twin.History/src/Runtime/Config.cs
  services/src/Microsoft.Azure.IIoT.Services.OpcUa.Twin.History/src/Startup.cs
  services/src/Microsoft.Azure.IIoT.Services.OpcUa.Twin/src/Runtime/Config.cs
  services/src/Microsoft.Azure.IIoT.Services.OpcUa.Twin/src/Startup.cs
  services/src/Microsoft.Azure.IIoT.Services.OpcUa.Vault/src/Runtime/Config.cs
  services/src/Microsoft.Azure.IIoT.Services.OpcUa.Vault/src/Startup.cs
Labels: bug
